#!/bin/bash

root=$(dirname $(dirname $0))
rebuild=$root/.rebuild
dist="$root/heroic-dist"

JVM_OPTS=${JVM_OPTS:-""}

MVN=${MVN:-mvn}
MVN_OPTS=${MVN_OPTS:-"-B -V"}

dist_jar="$dist/target/heroic-dist-0.0.1-SNAPSHOT.jar"
classpath_file="$dist/target/.classpath"

while true; do
    if [[ $1 == '-debug' ]]; then
        JVM_OPTS="$JVM_OPTS -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=y"
        JVM_OPTS="$JVM_OPTS -Dloglevel=TRACE"
        shift
    fi

    if [[ $1 == '-rebuild' ]]; then
        touch $rebuild
        shift
    fi

    break
done

if [[ -d $dist ]]; then
    if [[ ! -f $rebuild ]]; then
        $root/tools/install-repackaged
        touch $rebuild
    fi

    if [[ ! -f $dist_jar || $rebuild -nt $dist_jar ]]; then
        (
            cd $root
            $MVN $MVN_OPTS \
                -P '!shade,build-classpath' -D maven.test.skip=true \
                clean package
        )
    fi

    if [[ ! -f $dist_jar ]]; then
        echo "No such jar: $dist_jar" 1>&2
        exit 1
    fi

    if [[ ! -f $classpath_file ]]; then
        echo "No such file: $classpath_file" 1>&2
        exit 1
    fi
fi

CLASSPATH="$(cat $classpath_file):$dist_jar"

echo "Note: run \`touch $rebuild\` to cause a rebuild next run"
exec java -cp "$CLASSPATH" $JVM_OPTS com.spotify.heroic.HeroicShell "$@"
