#!/usr/bin/env python3

import sys
import os
import requests
import yaml
import argparse

settings = {
    "index": {
        "number_of_replicas": 1
    }
}

def setup_parser():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        '--host', help="Elasticsearch host to configure", required=True)

    parser.add_argument(
        '--index-base', help="Base index name to configure, i.e. <index-base>-*",
        default="heroic-querylog")

    return parser

def main():
    parser = setup_parser()

    ns = parser.parse_args()

    host = ns.host
    index_base = ns.index_base

    mapping_path = os.path.join(
        os.path.dirname(os.path.abspath(sys.argv[0])),
        'querylog_mappings.yaml')

    mappings = None

    with open(mapping_path) as f:
        mappings = yaml.load(f)

    for (type, mapping) in mappings.items():
        url = '{}/_template/{}-{}'.format(host, index_base, type)

        template = {
            "template": "{}-{}-*".format(index_base, type),
            "settings": settings,
            "mappings": {
                "entry": mapping
            }
        }

        response = requests.put(url, json=template)
        print(response.text)

if __name__ == "__main__":
    main()
